name: Lint Go
description: Run Go lint
inputs:
  go-version:
    description: Go version to use
    required: true
    default: "1.19"
  no-cache:
    description: Disable caching
    required: false
    default: "false"
  working-directory:
    description: Working directory
    required: false
    default: "."
  golangci-lint-version:
    description: golangci-lint version to use
    required: false
    default: "v1.50.1"
runs:
  using: "composite"
  steps:
    - name: Set up Go ${{ inputs.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ !inputs.no-cache }}}
        cache-dependency-path: ${{ inputs.working-directory }}
    - name: Test
      id: lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ inputs.golangci-lint-version }}
        working-directory: ${{ inputs.working-directory }}
