name: Generate Protobuf
description: Generate protobuf code
inputs:
  buf-version:
    description: buf version to use
    required: true
    default: "1.14.0"
  working-directory:
    description: Working directory
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set up buf ${{ inputs.buf-version }}
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}
        version: ${{ inputs.buf-version }}
    - name: Generate
      id: generate
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        find . -type d -name proto | while read -r dir; do
            (
                echo "Generating $dir"
                cd "$dir"
                buf generate
            )
        done
