name: Generate Protobuf
description: Generate protobuf code
inputs:
  buf-version:
    description: buf version to use
    required: true
    default: "1.14.0"
  no-cache:
    description: Disable caching
    required: false
    default: "false"
  working-directory:
    description: Working directory
    required: false
    default: "."
  generate-flags:
    description: Flags to pass to `go generate`
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up buf ${{ inputs.buf-version }}
      uses: bufbuild/buf-setup-action@${{ inputs.buf-version }}
      with:
        github_token: ${{ github.token }}
    - name: Generate
      id: generate
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        find . -type d -name proto | while read -r dir; do
            (
                echo "Generating $dir"
                cd "$dir"
                buf generate
            )
        done
